<?php

use Illuminate\Database\Seeder;

class MasterUnitKerjasTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('master_unit_kerjas')->delete();
        
        \DB::table('master_unit_kerjas')->insert(array (
            0 => 
            array (
                'id' => 1,
                'kd_unit' => 1,
                'name' => 'Divisi Regional Jawa Tengah',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'kd_unit' => 101,
                'name' => 'Kantor Divisi Regional Jawa Tengah',
                'pejabat' => 'Ub. Kepala Seksi Personalia',
                'alamat1' => 'Perum Perhutani',
                'alamat2' => 'Jl. Pahlawan No. 15 - 17',
                'kota' => 'Semarang',
                'kd_pos' => NULL,
                'provinsi' => 'Jawa Tengah',
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'kd_unit' => 102,
                'name' => 'SPAHW KALTIM',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'kd_unit' => 111,
                'name' => 'KPH Balapulang',
                'pejabat' => 'Kepala Urusan Personalia ',
                'alamat1' => 'KPH BALAPULANG PERUM PERHUTANI',
                'alamat2' => 'Jl. Raya Selatan No. 1',
                'kota' => 'Tegal',
                'kd_pos' => NULL,
                'provinsi' => 'Jawa Tengah',
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'kd_unit' => 112,
                'name' => 'KPH Blora',
                'pejabat' => 'Kepala Urusan Personalia',
                'alamat1' => 'KPH BLORA PERUM PERHUTANI',
                'alamat2' => 'Jl. Dr. Soetomo No. 56',
                'kota' => 'Blora',
                'kd_pos' => NULL,
                'provinsi' => 'Jawa Tengah',
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'kd_unit' => 113,
                'name' => 'KPH Banyumas Barat',
                'pejabat' => 'Kepala Urusan Personalia',
                'alamat1' => 'KPH BANYUMAS BARAT PERUM PERHUTANI',
                'alamat2' => 'Jl. Laksda Yos Sudarso',
                'kota' => 'Purwokerto',
                'kd_pos' => NULL,
                'provinsi' => 'Jawa Tengah',
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'kd_unit' => 114,
                'name' => 'KPH Banyumas Timur',
                'pejabat' => 'Kepala Urusan Personalia',
                'alamat1' => 'KPH BANYUMAS TIMUR',
                'alamat2' => 'Jl. Gatot Subroto',
                'kota' => 'Purwokerto',
                'kd_pos' => NULL,
                'provinsi' => 'Jawa Tengah',
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'kd_unit' => 115,
                'name' => 'KPH Cepu',
                'pejabat' => 'Kepala Urusan Personalia',
                'alamat1' => 'KPH CEPU PERUM PERHUTANI',
                'alamat2' => 'Jl. Sorogo',
                'kota' => 'Cepu',
                'kd_pos' => NULL,
                'provinsi' => 'Jawa Tengah',
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'kd_unit' => 116,
                'name' => 'KPH Gundih',
                'pejabat' => 'Kepala Urusan Personalia',
                'alamat1' => 'KPH GUNDIH PERUM PERHUTANI',
                'alamat2' => 'Pos Purwodadi telp 561',
                'kota' => 'Purwodadi',
                'kd_pos' => NULL,
                'provinsi' => 'Jawa Tengah',
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'kd_unit' => 117,
                'name' => 'KPH Kebonhardjo',
                'pejabat' => 'Kepala Urusan Personalia',
                'alamat1' => 'KPH KEBONHARDJO PERUM PERHUTANI',
                'alamat2' => 'Jl. Pos Rembang',
                'kota' => 'Kebonhardjo',
                'kd_pos' => NULL,
                'provinsi' => 'Jawa Tengah',
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'kd_unit' => 118,
                'name' => 'KPH Kedu Selatan',
                'pejabat' => 'Kepala Urusan Personalia',
                'alamat1' => 'KPH KEDU SELATAN PERUM PERHUTANI',
                'alamat2' => 'Jl. Ahmad Yani No. 23A',
                'kota' => 'Purworejo',
                'kd_pos' => NULL,
                'provinsi' => 'Jawa Tengah',
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'kd_unit' => 119,
                'name' => 'KPH Kendal',
                'pejabat' => 'Kepala Urusan Personalia',
                'alamat1' => 'KPH KENDAL PERUM PERHUTANI',
                'alamat2' => 'Jl. Raya No. 199',
                'kota' => 'Kendal',
                'kd_pos' => NULL,
                'provinsi' => 'Jawa Tengah',
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'kd_unit' => 120,
                'name' => 'KPH Kedu Utara',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'kd_unit' => 121,
                'name' => 'KPH Mantingan',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'kd_unit' => 122,
                'name' => 'KPH Pati',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'kd_unit' => 123,
                'name' => 'KPH Pekalongan Barat',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'kd_unit' => 124,
                'name' => 'KPH Pekalongan Timur',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'kd_unit' => 125,
                'name' => 'KPH Pemalang',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'kd_unit' => 126,
                'name' => 'KPH Purwodadi',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'kd_unit' => 127,
                'name' => 'KPH Randublatung',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'kd_unit' => 128,
                'name' => 'KPH Semarang',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'kd_unit' => 129,
                'name' => 'KPH Surakarta',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'kd_unit' => 130,
                'name' => 'KPH Telawa',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'kd_unit' => 140,
                'name' => 'PSA Sopeng',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'kd_unit' => 141,
                'name' => 'PSA Sopeng',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'kd_unit' => 150,
                'name' => 'Biro Perencanaan I',
                'pejabat' => 'Kepala Urusan Personalia',
                'alamat1' => 'BIRO PERENCANAAN UNIT I PERUM PERHUTANI',
                'alamat2' => 'Jl. Laksda Yos Sudarso 13',
                'kota' => 'Salatiga',
                'kd_pos' => NULL,
                'provinsi' => 'Jawa Tengah',
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'kd_unit' => 151,
                'name' => 'SPH I REMBANG',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'kd_unit' => 152,
                'name' => 'SPH II YOGYAKARTA',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'kd_unit' => 153,
                'name' => 'SPH III SALATIGA',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'kd_unit' => 154,
                'name' => 'SPH IV PEKALONGAN',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'kd_unit' => 160,
                'name' => 'IPKJ Cepu',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'kd_unit' => 170,
                'name' => 'IPK Brumbung',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'kd_unit' => 180,
                'name' => '--',
                'pejabat' => NULL,
                'alamat1' => 'JLN.RAYA MRANGGEN KM.15 ',
                'alamat2' => 'SEMARANG-PURWODADI NO.58',
                'kota' => 'Semarang',
                'kd_pos' => 59567,
                'provinsi' => 'Jawa Tengah',
                'telepon' => '0246722982',
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'kd_unit' => 181,
                'name' => 'KANTOR GM INDUSTRI KAYU 1 ',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'kd_unit' => 182,
                'name' => 'KBM KOMERSIAL KAYU PEKALONGAN',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                'kd_unit' => 183,
                'name' => 'KBM PPA I SEMARANG, JATENG',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'kd_unit' => 184,
                'name' => 'KBM KOMKY WILAYAH RANDUBLATUNG',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            37 => 
            array (
                'id' => 38,
                'kd_unit' => 185,
                'name' => 'KBM PERHUTANI DIVISI DGT & MKP',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            38 => 
            array (
                'id' => 39,
                'kd_unit' => 186,
                'name' => 'KBM KOMERSIAL KAYU 1 JAWA TENGAH',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            39 => 
            array (
                'id' => 40,
                'kd_unit' => 187,
                'name' => 'KBM INDUSTRI KAYU SUB CEPU',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            40 => 
            array (
                'id' => 41,
                'kd_unit' => 188,
                'name' => 'DIVISI KOMKY JAWA TENGAH',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            41 => 
            array (
                'id' => 42,
                'kd_unit' => 191,
                'name' => 'MAN. KOMKY PURWOKERTO',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            42 => 
            array (
                'id' => 43,
                'kd_unit' => 192,
                'name' => 'MAN. KOMKY CEPU',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            43 => 
            array (
                'id' => 44,
                'kd_unit' => 193,
                'name' => 'KBM INDUSTRI KAYU CEPU',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            44 => 
            array (
                'id' => 45,
                'kd_unit' => 194,
                'name' => 'KBM INDUSTRI KAYU 1 SUB BRUMBUNG',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            45 => 
            array (
                'id' => 46,
                'kd_unit' => 195,
                'name' => 'KBM INDUSTRY GT 1',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            46 => 
            array (
                'id' => 47,
                'kd_unit' => 196,
                'name' => 'KBM AGRIBISNIS 1 JATENG',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            47 => 
            array (
                'id' => 48,
                'kd_unit' => 197,
                'name' => 'KBM.Jasa Lingkungan & Produksi Lainnya',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            48 => 
            array (
                'id' => 49,
                'kd_unit' => 198,
                'name' => 'KBM TRADING UNIT I',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            49 => 
            array (
                'id' => 50,
                'kd_unit' => 2,
                'name' => 'Divisi Regional Jawa Timur',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            50 => 
            array (
                'id' => 51,
                'kd_unit' => 201,
                'name' => 'Kantor Unit II Jawa Timur',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            51 => 
            array (
                'id' => 52,
                'kd_unit' => 202,
                'name' => 'SPH NUSA TENG.TIMUR',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            52 => 
            array (
                'id' => 53,
                'kd_unit' => 211,
                'name' => 'KPH Banyuwangi Barat',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            53 => 
            array (
                'id' => 54,
                'kd_unit' => 212,
                'name' => 'KPH Banyuwangi Slt.',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            54 => 
            array (
                'id' => 55,
                'kd_unit' => 213,
                'name' => 'KPH Banyuwangi Utara',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            55 => 
            array (
                'id' => 56,
                'kd_unit' => 214,
                'name' => 'KPH Blitar',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            56 => 
            array (
                'id' => 57,
                'kd_unit' => 215,
                'name' => 'KPH Bojonegoro',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            57 => 
            array (
                'id' => 58,
                'kd_unit' => 216,
                'name' => 'KPH Bondowoso',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            58 => 
            array (
                'id' => 59,
                'kd_unit' => 217,
                'name' => 'KPH Jatirogo',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            59 => 
            array (
                'id' => 60,
                'kd_unit' => 218,
                'name' => 'KPH Jember',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            60 => 
            array (
                'id' => 61,
                'kd_unit' => 219,
                'name' => 'KPH Jombang',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            61 => 
            array (
                'id' => 62,
                'kd_unit' => 220,
                'name' => 'KPH Kediri',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            62 => 
            array (
                'id' => 63,
                'kd_unit' => 221,
                'name' => 'KPH Lawu. Ds',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            63 => 
            array (
                'id' => 64,
                'kd_unit' => 222,
                'name' => 'KPH Madiun',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            64 => 
            array (
                'id' => 65,
                'kd_unit' => 223,
                'name' => 'KPH Madura',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            65 => 
            array (
                'id' => 66,
                'kd_unit' => 224,
                'name' => 'KPH Malang',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            66 => 
            array (
                'id' => 67,
                'kd_unit' => 225,
                'name' => 'KPH Mojokerto',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            67 => 
            array (
                'id' => 68,
                'kd_unit' => 226,
                'name' => 'KPH Nganjuk',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            68 => 
            array (
                'id' => 69,
                'kd_unit' => 227,
                'name' => 'KPH Ngawi',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            69 => 
            array (
                'id' => 70,
                'kd_unit' => 228,
                'name' => 'KPH Padangan',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            70 => 
            array (
                'id' => 71,
                'kd_unit' => 229,
                'name' => 'KPH Pasuruan',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            71 => 
            array (
                'id' => 72,
                'kd_unit' => 230,
                'name' => 'KPH Parengan',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            72 => 
            array (
                'id' => 73,
                'kd_unit' => 231,
                'name' => 'KPH Probolinggo',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            73 => 
            array (
                'id' => 74,
                'kd_unit' => 232,
                'name' => 'KPH Saradan',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            74 => 
            array (
                'id' => 75,
                'kd_unit' => 233,
                'name' => 'KPH Tuban',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            75 => 
            array (
                'id' => 76,
                'kd_unit' => 250,
                'name' => 'Biro Perencanaan II',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            76 => 
            array (
                'id' => 77,
                'kd_unit' => 251,
                'name' => 'SPH I Bojonegoro',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            77 => 
            array (
                'id' => 78,
                'kd_unit' => 252,
                'name' => 'SPH II Madiun',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            78 => 
            array (
                'id' => 79,
                'kd_unit' => 253,
                'name' => 'SPH III Jombang',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            79 => 
            array (
                'id' => 80,
                'kd_unit' => 254,
                'name' => 'SPH IV Malang',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            80 => 
            array (
                'id' => 81,
                'kd_unit' => 255,
                'name' => 'SPH V Jember',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            81 => 
            array (
                'id' => 82,
                'kd_unit' => 260,
                'name' => 'IPKJ Gresik',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            82 => 
            array (
                'id' => 83,
                'kd_unit' => 270,
                'name' => 'KPE UNIT II',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            83 => 
            array (
                'id' => 84,
                'kd_unit' => 281,
                'name' => 'MAN. KOMKY BANYUWANGI',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            84 => 
            array (
                'id' => 85,
                'kd_unit' => 282,
                'name' => 'MAN. KOMKY KEDIRI',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            85 => 
            array (
                'id' => 86,
                'kd_unit' => 283,
                'name' => 'MAN. KOMKY MOJOKERTO',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            86 => 
            array (
                'id' => 87,
                'kd_unit' => 284,
                'name' => 'DIVISI INDUSTRI KAYU II JAWA TIMUR',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            87 => 
            array (
                'id' => 88,
                'kd_unit' => 285,
                'name' => 'KBM PPI KEDIRI',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            88 => 
            array (
                'id' => 89,
                'kd_unit' => 286,
                'name' => 'KBMKOMKY II JAWA TIMUR',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            89 => 
            array (
                'id' => 90,
                'kd_unit' => 287,
                'name' => 'MAN. KOMKY JEMBER',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            90 => 
            array (
                'id' => 91,
                'kd_unit' => 288,
                'name' => 'KBM PPA 2 JAWA TIMUR',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            91 => 
            array (
                'id' => 92,
                'kd_unit' => 289,
                'name' => 'KBM AGROFORESTRY 2 JATIM',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            92 => 
            array (
                'id' => 93,
                'kd_unit' => 291,
                'name' => 'MAN. KOMKY MADIUN',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            93 => 
            array (
                'id' => 94,
                'kd_unit' => 292,
                'name' => 'MAN. KOMKY BOJONEGORO',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            94 => 
            array (
                'id' => 95,
                'kd_unit' => 293,
                'name' => 'MAN. KOMKY PROBOLINGGO',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            95 => 
            array (
                'id' => 96,
                'kd_unit' => 294,
                'name' => 'KBM Industri Kayu Gresik',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            96 => 
            array (
                'id' => 97,
                'kd_unit' => 295,
                'name' => 'KBM INDUSTRY GT 2 ',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            97 => 
            array (
                'id' => 98,
                'kd_unit' => 296,
                'name' => 'KBM WISATA&JASA LINGKUNGAN 2 JATIM',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            98 => 
            array (
                'id' => 99,
                'kd_unit' => 297,
                'name' => 'KBM AGRI BISNIS',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            99 => 
            array (
                'id' => 100,
                'kd_unit' => 298,
                'name' => 'KBM TRADING &IKR',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            100 => 
            array (
                'id' => 101,
                'kd_unit' => 299,
                'name' => 'KBM INDUSTRY MKP ',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            101 => 
            array (
                'id' => 102,
                'kd_unit' => 3,
                'name' => 'Divisi Regional Jawa Barat dan Banten',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            102 => 
            array (
                'id' => 103,
                'kd_unit' => 301,
                'name' => 'Kantor Unit III Jawa Barat dan Banten',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            103 => 
            array (
                'id' => 104,
                'kd_unit' => 302,
                'name' => 'SPAHW KALBAR',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            104 => 
            array (
                'id' => 105,
                'kd_unit' => 311,
                'name' => 'KPH Bandung Selatan',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            105 => 
            array (
                'id' => 106,
                'kd_unit' => 312,
                'name' => 'KPH Bandung Utara',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            106 => 
            array (
                'id' => 107,
                'kd_unit' => 313,
                'name' => 'KPH Banten',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            107 => 
            array (
                'id' => 108,
                'kd_unit' => 314,
                'name' => 'KPH Bogor',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            108 => 
            array (
                'id' => 109,
                'kd_unit' => 315,
                'name' => 'KPH Ciamis',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            109 => 
            array (
                'id' => 110,
                'kd_unit' => 316,
                'name' => 'KPH Cianjur',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            110 => 
            array (
                'id' => 111,
                'kd_unit' => 317,
                'name' => 'KPH Garut',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            111 => 
            array (
                'id' => 112,
                'kd_unit' => 318,
                'name' => 'KPH Indramayu',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            112 => 
            array (
                'id' => 113,
                'kd_unit' => 319,
                'name' => 'KPH Kuningan',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            113 => 
            array (
                'id' => 114,
                'kd_unit' => 320,
                'name' => 'KPH Majalengka',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            114 => 
            array (
                'id' => 115,
                'kd_unit' => 321,
                'name' => 'KPH Purwakarta',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            115 => 
            array (
                'id' => 116,
                'kd_unit' => 322,
                'name' => 'KPH Sukabumi',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            116 => 
            array (
                'id' => 117,
                'kd_unit' => 323,
                'name' => 'KPH Sumedang',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            117 => 
            array (
                'id' => 118,
                'kd_unit' => 324,
                'name' => 'KPH Tasikmalaya',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            118 => 
            array (
                'id' => 119,
                'kd_unit' => 350,
                'name' => 'Biro Perencanaan III',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            119 => 
            array (
                'id' => 120,
                'kd_unit' => 351,
                'name' => 'SPH I Bogor',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            120 => 
            array (
                'id' => 121,
                'kd_unit' => 352,
                'name' => 'SPHT II Cianjur',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            121 => 
            array (
                'id' => 122,
                'kd_unit' => 353,
                'name' => 'SPH III Bandung',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            122 => 
            array (
                'id' => 123,
                'kd_unit' => 354,
                'name' => 'SPH IV Cirebon',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            123 => 
            array (
                'id' => 124,
                'kd_unit' => 381,
                'name' => 'DIV. WISATA DAN AGRIBISNIS',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            124 => 
            array (
                'id' => 125,
                'kd_unit' => 382,
                'name' => 'MAN. KOMKY BOGOR',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            125 => 
            array (
                'id' => 126,
                'kd_unit' => 383,
                'name' => 'MAN. KOMKY PERIANGAN',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            126 => 
            array (
                'id' => 127,
                'kd_unit' => 384,
                'name' => 'MAN. KOMKY CIREBON',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            127 => 
            array (
                'id' => 128,
                'kd_unit' => 385,
                'name' => 'KBM PPA 3 JANTEN',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            128 => 
            array (
                'id' => 129,
                'kd_unit' => 391,
                'name' => 'KBM KOMERSIAL KAYU JABAR',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            129 => 
            array (
                'id' => 130,
                'kd_unit' => 392,
                'name' => 'KBM Industri Kayu & Non Kayu Jabar/IGT',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            130 => 
            array (
                'id' => 131,
                'kd_unit' => 393,
                'name' => 'KBM JASA LINGKUNGAN & PRODUK LAIN/WISATA',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            131 => 
            array (
                'id' => 132,
                'kd_unit' => 394,
                'name' => 'KBM TRADING / IK 1',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            132 => 
            array (
                'id' => 133,
                'kd_unit' => 395,
                'name' => 'KBM AGRI BISNIS',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            133 => 
            array (
                'id' => 134,
                'kd_unit' => 396,
                'name' => 'KBM EJULA',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            134 => 
            array (
                'id' => 135,
                'kd_unit' => 397,
                'name' => 'KARET UNIT III JAWA BARAT/AGRO FORESTRY',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            135 => 
            array (
                'id' => 136,
                'kd_unit' => 398,
                'name' => 'SENTUL ECO-EDU TOURISM FORREST',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            136 => 
            array (
                'id' => 137,
                'kd_unit' => 399,
                'name' => 'KBM KIFC',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            137 => 
            array (
                'id' => 138,
                'kd_unit' => 777,
                'name' => 'ORANG-ORANG YANG TIDAK JELAS DIMANA',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            138 => 
            array (
                'id' => 139,
                'kd_unit' => 8,
                'name' => 'Kantor Direksi Perum Perhutani',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            139 => 
            array (
                'id' => 140,
                'kd_unit' => 800,
                'name' => 'PUSAT PERUM PERHUTANI',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            140 => 
            array (
                'id' => 141,
                'kd_unit' => 801,
                'name' => 'Kantor Pusat Jakarta',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            141 => 
            array (
                'id' => 142,
                'kd_unit' => 811,
                'name' => 'KBM PPA PUSAT',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            142 => 
            array (
                'id' => 143,
                'kd_unit' => 820,
                'name' => 'Puslitbang Cepu',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            143 => 
            array (
                'id' => 144,
                'kd_unit' => 821,
                'name' => 'Pusdiklat SDM Madiun',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            144 => 
            array (
                'id' => 145,
                'kd_unit' => 822,
                'name' => 'PALAWI',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            145 => 
            array (
                'id' => 146,
                'kd_unit' => 830,
                'name' => 'Pusbahnas',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            146 => 
            array (
                'id' => 147,
                'kd_unit' => 888,
                'name' => 'Pensiun Tunggu',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
            147 => 
            array (
                'id' => 148,
                'kd_unit' => 999,
                'name' => 'KPH Penampungan',
                'pejabat' => NULL,
                'alamat1' => NULL,
                'alamat2' => NULL,
                'kota' => NULL,
                'kd_pos' => NULL,
                'provinsi' => NULL,
                'telepon' => NULL,
                'keterangan' => NULL,
                'created_at' => '2020-04-21 21:52:05',
                'updated_at' => NULL,
            ),
        ));
        
        
    }
}