<?php

use Illuminate\Database\Seeder;

class MasterAlasanPensiunsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('master_alasan_pensiuns')->delete();

        \DB::table('master_alasan_pensiuns')->insert(array (
            0 =>
            array (
                'id' => 2,
                'kode' => 'AD',
                'name' => 'ALIH DANA KE DAN PENSIUN LAIN',
                'syarat_pensiun' => 0,
                'formula_mp' => 1102,
                'jenis_sk' => 1,
                'jenis_pensiun' => 1,
                'jenis_sisa_mk' => 1,
                'usia_faktor_sekarang' => 0,
                'usia_faktor_sekaligus' => 0,
                'kode_aktuaria' => '',
                'created_by' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            1 =>
            array (
                'id' => 3,
                'kode' => 'DPA',
                'name' => 'DUDA DARI PESERTA AKTIF MENINGGAL',
                'syarat_pensiun' => 0,
                'formula_mp' => 1112,
                'jenis_sk' => 1,
                'jenis_pensiun' => 8,
                'jenis_sisa_mk' => 1,
                'usia_faktor_sekarang' => 0,
                'usia_faktor_sekaligus' => 0,
                'kode_aktuaria' => 'PJ',
                'created_by' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            2 =>
            array (
                'id' => 4,
                'kode' => 'DPN',
                'name' => '',
                'syarat_pensiun' => 0,
                'formula_mp' => 1121,
                'jenis_sk' => 13,
                'jenis_pensiun' => 8,
                'jenis_sisa_mk' => 0,
                'usia_faktor_sekarang' => 0,
                'usia_faktor_sekaligus' => 0,
                'kode_aktuaria' => 'PJ',
                'created_by' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            3 =>
            array (
                'id' => 5,
                'kode' => 'JPA',
                'name' => 'JANDA DARI PESERTA AKTIF MENINGGAL',
                'syarat_pensiun' => 0,
                'formula_mp' => 1112,
                'jenis_sk' => 1,
                'jenis_pensiun' => 7,
                'jenis_sisa_mk' => 1,
                'usia_faktor_sekarang' => 0,
                'usia_faktor_sekaligus' => 0,
                'kode_aktuaria' => 'PJ',
                'created_by' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            4 =>
            array (
                'id' => 6,
                'kode' => 'JPA-M',
            'name' => 'JANDA DARI PESERTA AKTIF MENINGGAL (REVISI)',
                'syarat_pensiun' => 0,
                'formula_mp' => 1112,
                'jenis_sk' => 13,
                'jenis_pensiun' => 7,
                'jenis_sisa_mk' => 1,
                'usia_faktor_sekarang' => 0,
                'usia_faktor_sekaligus' => 0,
                'kode_aktuaria' => 'PJ',
                'created_by' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            5 =>
            array (
                'id' => 7,
                'kode' => 'JPC',
                'name' => 'JANDA DARI PENSIUN CACAT MININGGAL',
                'syarat_pensiun' => 0,
                'formula_mp' => 1121,
                'jenis_sk' => 13,
                'jenis_pensiun' => 7,
                'jenis_sisa_mk' => 0,
                'usia_faktor_sekarang' => 0,
                'usia_faktor_sekaligus' => 0,
                'kode_aktuaria' => 'PJ',
                'created_by' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            6 =>
            array (
                'id' => 8,
                'kode' => 'JPD',
                'name' => 'JANDA DARI PENSIUN DIPERCEPAT MENINGGAL',
                'syarat_pensiun' => 0,
                'formula_mp' => 1121,
                'jenis_sk' => 13,
                'jenis_pensiun' => 7,
                'jenis_sisa_mk' => 0,
                'usia_faktor_sekarang' => 0,
                'usia_faktor_sekaligus' => 0,
                'kode_aktuaria' => 'PJ',
                'created_by' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            7 =>
            array (
                'id' => 9,
                'kode' => 'JPN',
                'name' => 'JANDA DARI PENSIUN NORMAL MENINGGAL',
                'syarat_pensiun' => 0,
                'formula_mp' => 1121,
                'jenis_sk' => 13,
                'jenis_pensiun' => 7,
                'jenis_sisa_mk' => 0,
                'usia_faktor_sekarang' => 0,
                'usia_faktor_sekaligus' => 0,
                'kode_aktuaria' => 'PJ',
                'created_by' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            8 =>
            array (
                'id' => 10,
                'kode' => 'JPN-M',
                'name' => 'JANDA DARI PENSIUN NORMAL MENINGGAL (REVISI',
                    'syarat_pensiun' => 0,
                    'formula_mp' => 1982,
                    'jenis_sk' => 13,
                    'jenis_pensiun' => 7,
                    'jenis_sisa_mk' => 0,
                    'usia_faktor_sekarang' => 0,
                    'usia_faktor_sekaligus' => 0,
                    'kode_aktuaria' => 'JP',
                    'created_by' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
                9 =>
                array (
                    'id' => 11,
                    'kode' => 'JPS',
                    'name' => 'JANDA PENSIUN-SEKALIGUS',
                    'syarat_pensiun' => 0,
                    'formula_mp' => 1981,
                    'jenis_sk' => 13,
                    'jenis_pensiun' => 7,
                    'jenis_sisa_mk' => 0,
                    'usia_faktor_sekarang' => 0,
                    'usia_faktor_sekaligus' => 1,
                    'kode_aktuaria' => 'jp',
                    'created_by' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
                10 =>
                array (
                    'id' => 12,
                    'kode' => 'JPT',
                    'name' => 'JANDA DARI PENSIUN DITUNDA MENINGGAL',
                    'syarat_pensiun' => 0,
                    'formula_mp' => 1111,
                    'jenis_sk' => 13,
                    'jenis_pensiun' => 7,
                    'jenis_sisa_mk' => 0,
                    'usia_faktor_sekarang' => 0,
                    'usia_faktor_sekaligus' => 0,
                    'kode_aktuaria' => 'PJ',
                    'created_by' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
                11 =>
                array (
                    'id' => 13,
                    'kode' => 'JPW',
                    'name' => 'JANDA DARI PENSIUN WAJIB',
                    'syarat_pensiun' => 0,
                    'formula_mp' => 1121,
                    'jenis_sk' => 13,
                    'jenis_pensiun' => 7,
                    'jenis_sisa_mk' => 0,
                    'usia_faktor_sekarang' => 0,
                    'usia_faktor_sekaligus' => 0,
                    'kode_aktuaria' => 'PJ',
                    'created_by' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
                12 =>
                array (
                    'id' => 14,
                    'kode' => 'PA',
                    'name' => 'ANAK DARI PESERTA AKTIF MENINGGAL',
                    'syarat_pensiun' => 0,
                    'formula_mp' => 1112,
                    'jenis_sk' => 1,
                    'jenis_pensiun' => 9,
                    'jenis_sisa_mk' => 1,
                    'usia_faktor_sekarang' => 0,
                    'usia_faktor_sekaligus' => 0,
                    'kode_aktuaria' => 'PA',
                    'created_by' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
                13 =>
                array (
                    'id' => 15,
                    'kode' => 'PAW',
                    'name' => 'PENSIUN TANPA ISTRI/ANAK',
                    'syarat_pensiun' => 1,
                    'formula_mp' => 1112,
                    'jenis_sk' => 1,
                    'jenis_pensiun' => 29,
                    'jenis_sisa_mk' => 1,
                    'usia_faktor_sekarang' => 0,
                    'usia_faktor_sekaligus' => 0,
                    'kode_aktuaria' => '',
                    'created_by' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
                14 =>
                array (
                    'id' => 16,
                    'kode' => 'PC',
                    'name' => 'PENSIUN CACAT',
                    'syarat_pensiun' => 0,
                    'formula_mp' => 1011,
                    'jenis_sk' => 1,
                    'jenis_pensiun' => 3,
                    'jenis_sisa_mk' => 1,
                    'usia_faktor_sekarang' => 0,
                    'usia_faktor_sekaligus' => 0,
                    'kode_aktuaria' => 'PP',
                    'created_by' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
                15 =>
                array (
                    'id' => 17,
                    'kode' => 'PDP',
                    'name' => 'Pensiun Dipercepat',
                    'syarat_pensiun' => 3,
                    'formula_mp' => 1011,
                    'jenis_sk' => 1,
                    'jenis_pensiun' => 5,
                    'jenis_sisa_mk' => 0,
                    'usia_faktor_sekarang' => 0,
                    'usia_faktor_sekaligus' => 0,
                    'kode_aktuaria' => 'PP',
                    'created_by' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
                16 =>
                array (
                    'id' => 18,
                    'kode' => 'PDP-M',
                'name' => 'Pensiun Dipercepat (REVISI)',
                    'syarat_pensiun' => 3,
                    'formula_mp' => 1011,
                    'jenis_sk' => 13,
                    'jenis_pensiun' => 5,
                    'jenis_sisa_mk' => 0,
                    'usia_faktor_sekarang' => 0,
                    'usia_faktor_sekaligus' => 0,
                    'kode_aktuaria' => 'PP',
                    'created_by' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
                17 =>
                array (
                    'id' => 19,
                    'kode' => 'PI',
                    'name' => 'PENGEMBALIAN IURAN',
                    'syarat_pensiun' => 0,
                    'formula_mp' => 1991,
                    'jenis_sk' => 1,
                    'jenis_pensiun' => 1,
                    'jenis_sisa_mk' => 0,
                    'usia_faktor_sekarang' => 0,
                    'usia_faktor_sekaligus' => 0,
                    'kode_aktuaria' => '',
                    'created_by' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
                18 =>
                array (
                    'id' => 20,
                    'kode' => 'PN',
                    'name' => 'Pensiun Normal',
                    'syarat_pensiun' => 1,
                    'formula_mp' => 1001,
                    'jenis_sk' => 1,
                    'jenis_pensiun' => 1,
                    'jenis_sisa_mk' => 0,
                    'usia_faktor_sekarang' => 0,
                    'usia_faktor_sekaligus' => 0,
                    'kode_aktuaria' => 'PP',
                    'created_by' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
                19 =>
                array (
                    'id' => 21,
                    'kode' => 'PN-M',
                'name' => 'PENSIUN NORMAL USIA >= 56 THN (REVISI)',
                    'syarat_pensiun' => 1,
                    'formula_mp' => 1001,
                    'jenis_sk' => 13,
                    'jenis_pensiun' => 1,
                    'jenis_sisa_mk' => 0,
                    'usia_faktor_sekarang' => 0,
                    'usia_faktor_sekaligus' => 0,
                    'kode_aktuaria' => 'PP',
                    'created_by' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
                20 =>
                array (
                    'id' => 22,
                    'kode' => 'PNSM',
                    'name' => 'PENSIUN NORMAL',
                    'syarat_pensiun' => 1,
                    'formula_mp' => 1001,
                    'jenis_sk' => 13,
                    'jenis_pensiun' => 1,
                    'jenis_sisa_mk' => 0,
                    'usia_faktor_sekarang' => 0,
                    'usia_faktor_sekaligus' => 0,
                    'kode_aktuaria' => 'PN',
                    'created_by' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
                21 =>
                array (
                    'id' => 23,
                    'kode' => 'PS',
                    'name' => 'PENSIUN SEKALIGUS',
                    'syarat_pensiun' => 0,
                    'formula_mp' => 1981,
                    'jenis_sk' => 1,
                    'jenis_pensiun' => 1,
                    'jenis_sisa_mk' => 1,
                    'usia_faktor_sekarang' => 0,
                    'usia_faktor_sekaligus' => 0,
                    'kode_aktuaria' => 'PP',
                    'created_by' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
                22 =>
                array (
                    'id' => 24,
                    'kode' => 'PSM',
                'name' => 'PENSIUN SEMU (USIA 56 Thn)',
                    'syarat_pensiun' => 0,
                    'formula_mp' => 0,
                    'jenis_sk' => 1,
                    'jenis_pensiun' => 1,
                    'jenis_sisa_mk' => 0,
                    'usia_faktor_sekarang' => 0,
                    'usia_faktor_sekaligus' => 0,
                    'kode_aktuaria' => 'PN',
                    'created_by' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
                23 =>
                array (
                    'id' => 25,
                    'kode' => 'PT',
                    'name' => 'PENSIUN DITUNDA',
                    'syarat_pensiun' => 5,
                    'formula_mp' => 0,
                    'jenis_sk' => 1,
                    'jenis_pensiun' => 10,
                    'jenis_sisa_mk' => 0,
                    'usia_faktor_sekarang' => 4,
                    'usia_faktor_sekaligus' => 4,
                    'kode_aktuaria' => 'PT',
                    'created_by' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
                24 =>
                array (
                    'id' => 26,
                    'kode' => 'PTR',
                    'name' => 'Pensiun Masa Tunda - Realisasi',
                    'syarat_pensiun' => 3,
                    'formula_mp' => 1011,
                    'jenis_sk' => 12,
                    'jenis_pensiun' => 6,
                    'jenis_sisa_mk' => 0,
                    'usia_faktor_sekarang' => 0,
                    'usia_faktor_sekaligus' => 0,
                    'kode_aktuaria' => 'PTR',
                    'created_by' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
                25 =>
                array (
                    'id' => 27,
                    'kode' => 'PTS',
                    'name' => 'Pensiun Putus ',
                    'syarat_pensiun' => 0,
                    'formula_mp' => 0,
                    'jenis_sk' => 13,
                    'jenis_pensiun' => 1,
                    'jenis_sisa_mk' => 0,
                    'usia_faktor_sekarang' => 0,
                    'usia_faktor_sekaligus' => 0,
                    'kode_aktuaria' => '',
                    'created_by' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
                26 =>
                array (
                    'id' => 28,
                    'kode' => 'PUTUS',
                    'name' => 'Tidak ada ahli waris',
                    'syarat_pensiun' => 0,
                    'formula_mp' => 0,
                    'jenis_sk' => 1,
                    'jenis_pensiun' => 1,
                    'jenis_sisa_mk' => 0,
                    'usia_faktor_sekarang' => 0,
                    'usia_faktor_sekaligus' => 0,
                    'kode_aktuaria' => '',
                    'created_by' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
                27 =>
                array (
                    'id' => 29,
                    'kode' => 'PW',
                    'name' => 'PENSIUN WAJIB',
                    'syarat_pensiun' => 0,
                    'formula_mp' => 1011,
                    'jenis_sk' => 1,
                    'jenis_pensiun' => 1,
                    'jenis_sisa_mk' => 0,
                    'usia_faktor_sekarang' => 0,
                    'usia_faktor_sekaligus' => 0,
                    'kode_aktuaria' => 'PP',
                    'created_by' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
                28 =>
                array (
                    'id' => 30,
                    'kode' => 'PY',
                    'name' => 'YATIM DARI PESERTA AKTIF',
                    'syarat_pensiun' => 0,
                    'formula_mp' => 1201,
                    'jenis_sk' => 0,
                    'jenis_pensiun' => 9,
                    'jenis_sisa_mk' => 0,
                    'usia_faktor_sekarang' => 0,
                    'usia_faktor_sekaligus' => 0,
                    'kode_aktuaria' => 'PA',
                    'created_by' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
                29 =>
                array (
                    'id' => 31,
                    'kode' => 'YPA',
                    'name' => 'ANAK DARI PESERTA AKTIF',
                    'syarat_pensiun' => 0,
                    'formula_mp' => 1112,
                    'jenis_sk' => 1,
                    'jenis_pensiun' => 9,
                    'jenis_sisa_mk' => 1,
                    'usia_faktor_sekarang' => 0,
                    'usia_faktor_sekaligus' => 1,
                    'kode_aktuaria' => 'PA',
                    'created_by' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
                30 =>
                array (
                    'id' => 32,
                    'kode' => 'YPC',
                    'name' => 'ANAK DARI PENSIUN CACAT MENINGGAL',
                    'syarat_pensiun' => 0,
                    'formula_mp' => 1221,
                    'jenis_sk' => 13,
                    'jenis_pensiun' => 9,
                    'jenis_sisa_mk' => 0,
                    'usia_faktor_sekarang' => 0,
                    'usia_faktor_sekaligus' => 0,
                    'kode_aktuaria' => 'PA',
                    'created_by' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
                31 =>
                array (
                    'id' => 33,
                    'kode' => 'YPDP',
                    'name' => 'ANAK DARI PENSIUN DIPERCEPAT MENINGGAL',
                    'syarat_pensiun' => 0,
                    'formula_mp' => 1221,
                    'jenis_sk' => 13,
                    'jenis_pensiun' => 9,
                    'jenis_sisa_mk' => 0,
                    'usia_faktor_sekarang' => 0,
                    'usia_faktor_sekaligus' => 0,
                    'kode_aktuaria' => 'PA',
                    'created_by' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
                32 =>
                array (
                    'id' => 34,
                    'kode' => 'YPJ',
                    'name' => 'ANAK DARI PENSIUN JANDA/DUDA MENINGGAL',
                    'syarat_pensiun' => 0,
                    'formula_mp' => 1222,
                    'jenis_sk' => 13,
                    'jenis_pensiun' => 9,
                    'jenis_sisa_mk' => 0,
                    'usia_faktor_sekarang' => 0,
                    'usia_faktor_sekaligus' => 0,
                    'kode_aktuaria' => 'PA',
                    'created_by' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
                33 =>
                array (
                    'id' => 35,
                    'kode' => 'YPN',
                    'name' => 'ANAK DARI PENSIUN NORMAL MENINGGAL',
                    'syarat_pensiun' => 0,
                    'formula_mp' => 1221,
                    'jenis_sk' => 12,
                    'jenis_pensiun' => 9,
                    'jenis_sisa_mk' => 0,
                    'usia_faktor_sekarang' => 0,
                    'usia_faktor_sekaligus' => 0,
                    'kode_aktuaria' => 'PA',
                    'created_by' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
                34 =>
                array (
                    'id' => 36,
                    'kode' => 'YPS',
                    'name' => 'MP Sekaligus dari Pensun Anak',
                    'syarat_pensiun' => 0,
                    'formula_mp' => 1981,
                    'jenis_sk' => 13,
                    'jenis_pensiun' => 9,
                    'jenis_sisa_mk' => 0,
                    'usia_faktor_sekarang' => 1,
                    'usia_faktor_sekaligus' => 1,
                    'kode_aktuaria' => 'PA',
                    'created_by' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
                35 =>
                array (
                    'id' => 37,
                    'kode' => 'YPT',
                    'name' => 'ANAK DARI PENSIUNDITUNDA MENINGGAL',
                    'syarat_pensiun' => 0,
                    'formula_mp' => 1211,
                    'jenis_sk' => 13,
                    'jenis_pensiun' => 9,
                    'jenis_sisa_mk' => 0,
                    'usia_faktor_sekarang' => 0,
                    'usia_faktor_sekaligus' => 0,
                    'kode_aktuaria' => 'PA',
                    'created_by' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
                36 =>
                array (
                    'id' => 38,
                    'kode' => 'ZZZ',
                    'name' => 'KOREKSI DATA',
                    'syarat_pensiun' => 0,
                    'formula_mp' => 0,
                    'jenis_sk' => 1,
                    'jenis_pensiun' => 1,
                    'jenis_sisa_mk' => 0,
                    'usia_faktor_sekarang' => 0,
                    'usia_faktor_sekaligus' => 0,
                    'kode_aktuaria' => '',
                    'created_by' => 0,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            ));


    }
}
